apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-6-service
  labels:
    app: sprint-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprint-6
  template:
    metadata:
      labels:
        app: sprint-6
    spec:
      containers:
        - name: sprint-6
          image: shestera/scaletestapp
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "30Mi"

